# -*- coding: utf-8 -*-
IDENT = {
"administrativo": ("Direito administrativo: seus direitos diante do Estado",
 "Responsabilidade do Estado por dano de agente público, desapropriação, processo administrativo e revisão de atos: o que contestar e em que prazo agir.",
 "Quando a decisão do poder público afeta você",
 "Responsabilidade do Estado por dano, desapropriação, processo administrativo disciplinar e revisão de atos da Administração."),
"aereo": ("Voo atrasado, cancelado ou bagagem extraviada",
 "Atraso, cancelamento, overbooking e extravio de bagagem: que assistência a companhia aérea deve prestar, quando cabe reembolso e como registrar a reclamação.",
 "Seu voo atrasou, foi cancelado ou a bagagem sumiu",
 "Atraso, cancelamento, overbooking, extravio de bagagem e cobrança na remarcação: o que a companhia deve a você em cada situação."),
"autonomos": ("Autônomos e apps: contrato, bloqueio e pagamento",
 "Quem presta serviço sem vínculo de emprego: cancelamento depois do serviço começar, bloqueio de conta em aplicativo e como provar o trabalho feito para receber.",
 "Trabalho por conta própria e disputas com plataformas",
 "Cancelamento de serviço já iniciado, bloqueio de conta em aplicativo por avaliação e prova do serviço prestado por quem trabalha sem vínculo."),
"bancario": ("Direito bancário: cobrança, empréstimo e negativação",
 "Empréstimo que você não contratou, juros acima da média do mercado, negativação indevida, tarifas e Open Finance: como contestar e o que reunir antes.",
 "Cobrança, empréstimo ou negativação que você não reconhece",
 "Consignado contratado por fraude, juros acima da média, negativação indevida, tarifas e compartilhamento de dados no Open Finance."),
"cidadania": ("Nome, nacionalidade e documentos de cidadania",
 "Mudança de nome, opção de nacionalidade, reunião familiar de estrangeiro, apostilamento de certidão e passaporte de menor: documentos e caminho de cada pedido.",
 "Mudança de nome, nacionalidade e situação migratória",
 "Mudança de nome, opção de nacionalidade, reunião familiar de estrangeiro ou refugiado, apostilamento de certidão e passaporte de menor."),
"constitucional": ("Constituição: os conceitos por trás de uma decisão",
 "Poder constituinte, eficácia das normas constitucionais, direito adquirido e vedação ao retrocesso: o fundamento de uma decisão, em linguagem direta.",
 "Os conceitos da Constituição por trás de uma decisão",
 "Poder constituinte, eficácia das normas, direito adquirido e vedação ao retrocesso social, explicados para quem precisa entender o fundamento."),
"consumidor": ("Direito do consumidor: compra, serviço e cobrança",
 "Produto com defeito, cobrança indevida, cancelamento dificultado, propaganda enganosa e superendividamento: o que exigir da empresa e como formalizar.",
 "A compra, o serviço ou o contrato não saiu como prometido",
 "Produto com defeito fora da garantia, cobrança indevida, cancelamento dificultado, propaganda enganosa e superendividamento."),
"criminal": ("Direito criminal: processo penal e limites da lei",
 "O que caracteriza um crime, quando cabe prisão em flagrante, a diferença entre dolo e culpa e como anda um processo penal, da investigação ao julgamento.",
 "Entender um processo penal e os limites da lei",
 "O que caracteriza um crime, quando cabe prisão em flagrante, dolo e culpa, garantias no interrogatório e o andamento de um caso."),
"digital": ("Direito digital: golpes, imagem e redes sociais",
 "Uso indevido de imagem, perfil invadido, golpe com Pix ou aposta online, conteúdo difamatório e responsabilidade da plataforma pela demora em remover.",
 "Problemas que nascem na internet e nas redes sociais",
 "Uso indevido de imagem, perfil invadido, golpe envolvendo Pix ou aposta online, conteúdo difamatório e publicidade enganosa de influenciador."),
"educacao": ("Direito educacional: mensalidade, multa e bolsa",
 "Multa por cancelamento fora do prazo, negativação com pagamento em dia, cobrança acima do valor da matrícula e suspensão de bolsa: como contestar cada uma.",
 "A cobrança ou a decisão da instituição de ensino",
 "Multa por cancelamento fora do prazo de fidelidade, negativação apesar de pagamento em dia, cobrança acima do valor divulgado e suspensão de bolsa."),
"empresarial": ("Direito empresarial: sócios, contratos e cobrança",
 "Título protestado, cliente que não paga, saída de sócio, holding familiar, recuperação judicial e disputa contratual: as decisões que travam um negócio.",
 "Questões que a rotina da empresa não resolve sozinha",
 "Título protestado indevidamente, cliente que não paga, saída de sócio, estrutura de holding familiar e disputa contratual com fornecedor."),
"familia": ("Direito de família: guarda, pensão e partilha",
 "Separação e partilha de bens, guarda e pensão dos filhos, reconhecimento de paternidade, curatela e violência doméstica: o caminho de cada situação.",
 "Vínculos que mudaram ou estão em disputa",
 "Separação e partilha de bens, guarda e pensão alimentícia dos filhos, reconhecimento de paternidade, curatela e violência doméstica."),
"glossario": ("Glossário jurídico: termos explicados na prática",
 "Usucapião, dolo eventual, inventário extrajudicial, amicus curiae: cada verbete explica o termo dentro da situação real em que ele aparece, com fonte oficial.",
 "O termo técnico que travou a sua leitura",
 "Cada verbete explica o que a expressão significa dentro da situação concreta em que ela aparece — não a definição de dicionário."),
"imobiliario": ("Direito imobiliário: compra, aluguel e condomínio",
 "Entrega em atraso, vício de construção, arras, ITBI, caução, denúncia vazia e multa de condomínio: o que cabe exigir em cada etapa do negócio imobiliário.",
 "A compra, a obra ou o aluguel saiu do combinado",
 "Entrega em atraso, vício de construção, arras e ITBI, caução e denúncia vazia na locação, multa e vaga de garagem no condomínio."),
"inpi": ("Marca e patente no INPI: registro e defesa",
 "Classe do pedido, marca nominativa ou mista, recurso contra indeferimento e réplica de produto no mercado: como registrar e como defender o que já é seu.",
 "Registrar ou defender marca, patente ou desenho industrial",
 "Classe do pedido, marca nominativa ou mista, recurso contra indeferimento, réplica de produto no mercado e barreiras em marketplace."),
"investimentos": ("Investidor: corretora, plataforma e previdência",
 "Promessa de rentabilidade garantida, plataforma sem registro no Brasil, liquidação de exchange e taxa cobrada sem clareza: o que verificar e como reclamar.",
 "Disputas com corretoras e plataformas de investimento",
 "Promessa indevida de rentabilidade garantida, plataforma sem registro no Brasil, liquidação de exchange e taxa cobrada sem informação clara."),
"leis": ("Leis explicadas: o artigo aplicado ao seu caso",
 "Artigos do CDC, da legislação previdenciária, do Código Civil e da CLT explicados a partir de uma pergunta concreta — sem substituir a leitura da norma.",
 "O dispositivo legal explicado a partir de uma dúvida",
 "Artigos do CDC, da legislação previdenciária, do Código Civil e da CLT explicados a partir de uma pergunta concreta, sem substituir a norma original."),
"lgpd": ("LGPD: seus dados pessoais e o dever da empresa",
 "Vazamento de dados, câmera invadindo a privacidade, uso de currículo sem consentimento, direito de correção e exclusão e o que a empresa precisa cumprir.",
 "Dados usados sem autorização e obrigações da empresa",
 "Vazamento, câmera invadindo a privacidade, uso de currículo sem consentimento, direitos de correção e exclusão e resposta a incidentes."),
"previdenciario": ("INSS: aposentadoria, pensão e benefício negado",
 "Aposentadoria, pensão por morte, auxílio por incapacidade e BPC: o que fazer com pedido negado, CNIS incompleto, perícia contrária ou vínculo faltando.",
 "O pedido no INSS foi negado ou travou",
 "Aposentadoria, pensão por morte, auxílio por incapacidade e BPC: pedido negado, CNIS incompleto, perícia contrária e revisão de benefício."),
"procedimentos": ("Passo a passo de trâmites e atos do processo",
 "Emitir certidão, tirar a primeira CNH, abrir MEI, assinar pelo gov.br, reagir a bloqueio judicial e apresentar contestação: o passo a passo de cada trâmite.",
 "O trâmite que você precisa concluir sozinho",
 "Emitir certidão, tirar a primeira CNH, abrir MEI, assinar documento pelo gov.br, reagir a bloqueio via Sisbajud e atos processuais específicos."),
"saude": ("Plano de saúde: negativa, carência e reajuste",
 "Negativa de exame ou cirurgia, carência, portabilidade, reembolso, descredenciamento do médico no meio do tratamento e reajuste: o que o contrato pode limitar.",
 "O plano negou, atrasou ou limitou a cobertura",
 "Negativa de exame ou cirurgia, carência e portabilidade, reembolso, descredenciamento do médico durante o tratamento e reajuste da mensalidade."),
"seguros": ("Seguro negado ou pago a menos: o que fazer",
 "Sinistro de veículo, DPVAT, seguro de vida e residencial: por que a seguradora recusa, o que a cláusula realmente cobre e como contestar o valor pago.",
 "A seguradora negou, demorou ou pagou menos",
 "Sinistro de veículo, DPVAT, seguro de vida e residencial: cobertura, agravamento de risco, recusa e a interpretação das cláusulas do contrato."),
"servidor": ("Servidor público: PAD, aposentadoria e concurso",
 "Atraso de vencimentos, processo administrativo disciplinar, regra de transição da aposentadoria, readaptação, licenças e cadastro de reserva em concurso.",
 "Questões do regime estatutário e do concurso público",
 "Atraso de vencimentos, processo administrativo disciplinar, regra de transição da aposentadoria, readaptação por saúde, licenças e concurso."),
"sucessoes": ("Herança e inventário: partilha, testamento e bens",
 "Inventário judicial ou extrajudicial, deveres do inventariante, cálculo da legítima, testamento e doações em vida que voltam para a partilha da herança.",
 "A herança depois de uma morte: quem recebe o quê",
 "Inventário judicial ou extrajudicial, prestação de contas do inventariante, cálculo da legítima e doações em vida que entram na partilha."),
"sumulas": ("Súmulas do STF e do STJ explicadas caso a caso",
 "Cada súmula explicada a partir de uma pergunta concreta: o que ela decide, o que fica de fora do entendimento e a quem ele se aplica hoje.",
 "O que a súmula decide e até onde ela alcança",
 "Cada texto explica o que o entendimento consolidado decide, de onde ele veio e em que situação concreta ele costuma ser aplicado."),
"telecom-energia": ("Conta de luz, internet e telefone: corte e cobrança",
 "Fatura fora do padrão, corte sem aviso, cobrança retroativa por consumo, dívida de morador anterior e golpe de troca de chip: prazos e como contestar.",
 "Cobrança, corte ou atendimento fora do esperado",
 "Fatura fora do padrão de consumo, corte sem aviso, cobrança retroativa, dívida de morador anterior e golpes que usam o nome da concessionária."),
"trabalhista": ("Direito do trabalho: horas extras, rescisão, assédio",
 "Horas extras não pagas, verba rescisória incorreta, assédio, doença ocupacional e estabilidade: o que exigir da empresa e o que ela não pode exigir de você.",
 "O que a empresa descumpriu na relação de emprego",
 "Horas extras não pagas, verba rescisória incorreta, assédio e discriminação, doença ocupacional e estabilidade não respeitada."),
"transito": ("Multa, CNH suspensa e recurso no Detran",
 "Recusa ao bafômetro, exame toxicológico, multa questionável, suspensão da CNH e recurso no Detran e no CETRAN: prazos e o caminho de cada defesa.",
 "Autuação, suspensão da CNH e processo no Detran",
 "Recusa ao bafômetro, exame toxicológico do motorista profissional, indeferimento no CETRAN, multa questionável e habilitação."),
"tributario": ("Tributário: MEI, Simples, ITBI e dívida fiscal",
 "MEI protestado, CND negada, DAS em atraso, ITBI, ITCMD e Simples Nacional: como regularizar a pendência fiscal que impede a empresa de operar.",
 "A cobrança ou a pendência fiscal que trava a atividade",
 "MEI protestado, CND negada, DAS em atraso, ITBI e ITCMD, Simples Nacional e a transição para o novo modelo de IBS e CBS."),
}
